#import:
#  - /path/to/newconfig.yml

window:
  padding:
    x: 8
    y: 8

  dynamic_padding: false
  opacity: 1
  dynamic_title: true
  multiplier: 3

# Font configuration
font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  bold:
    family: Hack Nerd Font Mono
    style: Bold

  italic:
    style: Italic
    family: Hack Nerd Font Mono

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 9.0

  offset:
    x: 0
    y: 0

  draw_bold_text_with_bright_colors: true

# The definition of color schemes.
schemes:
  gruvbox_material_hard_dark: &gruvbox
    primary:
      background: '#1d2021'
      foreground: '#d4be98'
    normal:
      black: '#32302f'
      red: '#ea6962'
      green: '#a9b665'
      yellow: '#d8a657'
      blue: '#7daea3'
      magenta: '#d3869b'
      cyan: '#89b482'
      white: '#d4be98'
    bright:
      black: '#32302f'
      red: '#ea6962'
      green: '#a9b665'
      yellow: '#d8a657'
      blue: '#7daea3'
      magenta: '#d3869b'
      cyan: '#89b482'
      white: '#d4be98'

  malte: &malte
    primary:
      background: '#101010'
      foreground: '#b9b9b9'
    normal:
      black: '#393939'
      red: '#ff9f95'
      green: '#e2ffc7'
      yellow: '#ffffb9'
      blue: '#a8ceea'
      magenta: '#e2b5cc'
      cyan: '#c2efff'
      white: '#dddddd'
    bright:
      black: '#474747'
      red: '#ff8d80'
      green: '#dbffb3'
      yellow: '#ffbe64'
      blue: '#7eb6ff'
      magenta: '#e296ff'
      cyan: '#9ce9ff'
      white: '#b9b9b9'

# Apply the color scheme.
colors: *gruvbox

cursor:
  custom_cursors_colors: true
  style:
    shape: Underline # [Block: ▇ | Underline: _  | Beam: |]
    blinking: On
    blink_interval: 250
    thickness: 4
